// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-25k17U2emDMNcv_d5MNPiGgyLvRXfSU',
    appId: '1:695931468120:web:eec6bc1f98dc14151d8d2d',
    messagingSenderId: '695931468120',
    projectId: 'whatsapp-20081',
    authDomain: 'whatsapp-20081.firebaseapp.com',
    storageBucket: 'whatsapp-20081.appspot.com',
    measurementId: 'G-B44E6MNLXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2VeOg7KwFvPnJpleLlbdNhsSkalKl8a0',
    appId: '1:695931468120:android:5957fd84054a0c441d8d2d',
    messagingSenderId: '695931468120',
    projectId: 'whatsapp-20081',
    storageBucket: 'whatsapp-20081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGHhW0-ga07lh0cAoP5gqUBCJwhtNHpP4',
    appId: '1:695931468120:ios:0668e6902a71974a1d8d2d',
    messagingSenderId: '695931468120',
    projectId: 'whatsapp-20081',
    storageBucket: 'whatsapp-20081.appspot.com',
    iosClientId: '695931468120-391iv5b203e4i8v9h2n849somlcoes6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGHhW0-ga07lh0cAoP5gqUBCJwhtNHpP4',
    appId: '1:695931468120:ios:0668e6902a71974a1d8d2d',
    messagingSenderId: '695931468120',
    projectId: 'whatsapp-20081',
    storageBucket: 'whatsapp-20081.appspot.com',
    iosClientId: '695931468120-391iv5b203e4i8v9h2n849somlcoes6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
